name: blast-binderized
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  #- qgrid 
  - pandas-datareader>=0.5.0
  - matplotlib>=2.1.1
  - seaborn
  - statsmodels
  - biopython
  - regex
  - blast>=2.7.1
  - papermill
  - plotly
